---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Provision VM from Template
    name: template
    inherits: 
    description: 
  fields:
  - Provision:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/Provision"
  - CheckProvisioned:
      value: "/Infrastructure/VM/Provisioning/StateMachines/Methods/CheckProvisioned"
  - ProtectVM:
      on_entry: 'update_provision_status(status => ''Protecting VM'') '
      on_exit: 'update_provision_status(status => ''Protecting VM Finished'') '
      on_error: 'update_provision_status(status => ''Error Protecting VM'') '
